services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hn_search
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    shm_size: 2g